//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLCS3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETCHUCVU
    {
        public string VC_MA { get; set; }
        public int CV_MA { get; set; }
        public System.DateTime NGAYBATDAUCHUCVU { get; set; }
        public System.DateTime NGAYKETTHUCCHUCVU { get; set; }
    
        public virtual CHUCVU CHUCVU { get; set; }
        public virtual VIENCHUC VIENCHUC { get; set; }
    }
}
