//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLCS3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HOATDONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOATDONG()
        {
            this.CHITIETHOATDONGs = new HashSet<CHITIETHOATDONG>();
        }
    
        public int HD_MA { get; set; }
        public string BM_MA { get; set; }
        public string HD_TEN { get; set; }
        public string HD_MOTA { get; set; }
        public Nullable<int> HD_SOTIET { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> HD_NGAYDIENRA { get; set; }
        public string HD_FILE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHOATDONG> CHITIETHOATDONGs { get; set; }
    }
}
