//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLCS3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHENTHUONGKYLUAT
    {
        public int KT_MA { get; set; }
        public string VC_MA { get; set; }
        public string KT_NOIDUNG { get; set; }
        public double KT_THUONG { get; set; }
    
        public virtual VIENCHUC VIENCHUC { get; set; }
    }
}
