//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLCS3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NLCS_QLHDCDEntities12 : DbContext
    {
        public NLCS_QLHDCDEntities12()
            : base("name=NLCS_QLHDCDEntities12")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BOMON> BOMONs { get; set; }
        public virtual DbSet<CHITIETCHUCVU> CHITIETCHUCVUs { get; set; }
        public virtual DbSet<CHITIETHOATDONG> CHITIETHOATDONGs { get; set; }
        public virtual DbSet<CHUCVU> CHUCVUs { get; set; }
        public virtual DbSet<HOATDONG> HOATDONGs { get; set; }
        public virtual DbSet<KHENTHUONGKYLUAT> KHENTHUONGKYLUATs { get; set; }
        public virtual DbSet<KHOA> KHOAs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<VIENCHUC> VIENCHUCs { get; set; }
    }
}
