//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLCS3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class VIENCHUC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VIENCHUC()
        {
            this.CHITIETCHUCVUs = new HashSet<CHITIETCHUCVU>();
            this.CHITIETHOATDONGs = new HashSet<CHITIETHOATDONG>();
            this.KHENTHUONGKYLUATs = new HashSet<KHENTHUONGKYLUAT>();
        }
    
        public string VC_MA { get; set; }
        public string BM_MA { get; set; }
        public string VC_ANH { get; set; }
        public string VC_HOTEN { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime VC_NGAYSINH { get; set; }
        public bool VC_GIOITINH { get; set; }
        public string VC_DIACHI { get; set; }
        public string VC_SDT { get; set; }
        public string VC_EMAIL { get; set; }
        public double VC_LUONG { get; set; }
        public string VC_QUYENSD { get; set; }
        [DataType(DataType.Password)]
        public string VC_MATKHAU { get; set; }
    
        public virtual BOMON BOMON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETCHUCVU> CHITIETCHUCVUs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHOATDONG> CHITIETHOATDONGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHENTHUONGKYLUAT> KHENTHUONGKYLUATs { get; set; }
    }
}
